repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: detect-private-key

  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-admon
          - mdformat-black
          - mdformat-deflist
          - mdformat-footnote
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-tables

  - repo: https://github.com/btford/write-good
    rev: v1.0.8
    hooks:
      - id: write-good
        args: [--no-passive]
