name: 🐛 Bug
description: Report a bug
title: '🐛 '
type: bug
labels:
  - bug
assignees:
  - herrbenesch
body:

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.
        Please fill in as much of the template below as you're able.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: I found a bug
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Version on the packge. (You can find the version via `import PKG; PKG.__version__`)
      placeholder: x.x.x
    validations:
      required: true

  - type: textarea
    id: stack-trace
    attributes:
      label: Stack trace
      description: If you have a stack track, please dump it here.
      placeholder: |
        ```
        Key Error: foo
        …
        ```
    validations:
      required: false

  - type: textarea
    id: bug-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to ___
        2. Click on ___
        3. Scroll down to ___
        4. See error
    validations:
      required: false

  - type: textarea
    id: bug-expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected the app to do X
    validations:
      required: true
